
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        rails: ['5.2.6', '6.0.3.7', '6.1.3.2']

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems20210506-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems20210506-
    - name: Bundle install
      env:
        RAILS_VERSION: ${{ matrix.rails }}
      run: |
        bundle config path vendor/bundle
        bundle install
    - name: Run tests
      run: bundle exec rake
