
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        blacklight_version: ['~> 8.0']
        ruby_version: ['3.2', '3.3', '3.4']
        rails_version: ['8.0.2']
        include:
          - ruby_version: '3.3'
            rails_version: '7.2.2.1'
            blacklight_version: '~> 7.0'
          - ruby_version: '3.4'
            rails_version: '8.0.2'
            blacklight_version: '9.0.0.beta1'
    name: test (blacklight ${{ matrix.blacklight_version }} / ruby ${{ matrix.ruby_version }} / rails ${{ matrix.rails_version }})
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      BLACKLIGHT_VERSION: ${{ matrix.blacklight_version }}
      ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test --css bootstrap'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Bundle install
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
      run: bundle install
    - name: Run tests
      run: bundle exec rake
